services:
  api:
    build: .
    depends_on:
      - redis
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "3000:3000"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  redis-seed:
    image: "redis:latest"
    depends_on:
      - redis
    volumes:
      - ./seed-data/:/seed-data:ro
    command: sh -c 'redis-cli -h redis -p 6379 < /seed-data/seed.redis'
  swagger-ui:
    image: "swaggerapi/swagger-ui"
    depends_on:
      - redis-seed
    volumes:
      - ./openapi/:/openapi:ro
    ports:
      - "80:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml